name: build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install system dependencies
        run: sudo apt-get install -y protobuf-compiler
      - name: Rust Build Cache
        uses: Swatinem/rust-cache@v2
      - name: Build (mvps-te)
        run: cargo build --locked --release -p mvps-te
      - name: Build (mvps-s3-gc)
        run: cargo build --locked --release -p mvps-s3-gc
      - name: Build (nbdstress)
        run: cargo build --locked --release -p nbdstress
      - name: Collect binaries
        run: |
          set -e
          mkdir build
          cd build
          cp ../target/release/mvps-te ./
          cp ../target/release/mvps-s3-gc ./
          cp ../target/release/nbdstress ./
          find . -type f -exec sha256sum '{}' ';'
      - name: Push binaries
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  build-aarch64:
    name: Build (AArch64)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - name: Install system dependencies
        run: sudo apt-get install -y protobuf-compiler
      - name: Install cargo-zigbuild
        run: pip3 install cargo-zigbuild
      - name: Rust Build Cache
        uses: Swatinem/rust-cache@v2
      - name: Build (mvps-te)
        run: cargo zigbuild --locked --release -p mvps-te --target aarch64-unknown-linux-gnu.2.19
      - name: Build (mvps-s3-gc)
        run: cargo zigbuild --locked --release -p mvps-s3-gc --target aarch64-unknown-linux-gnu.2.19
      - name: Build (nbdstress)
        run: cargo zigbuild --locked --release -p nbdstress --target aarch64-unknown-linux-gnu.2.19
      - name: Collect binaries
        run: |
          set -e
          mkdir build
          cd build
          cp ../target/aarch64-unknown-linux-gnu/release/mvps-te ./
          cp ../target/aarch64-unknown-linux-gnu/release/mvps-s3-gc ./
          cp ../target/aarch64-unknown-linux-gnu/release/nbdstress ./
          find . -type f -exec sha256sum '{}' ';'
      - name: Push binaries
        uses: actions/upload-artifact@v3
        with:
          name: build-aarch64
          path: ./build
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install system dependencies
        run: sudo apt-get install -y protobuf-compiler
      - name: Rust Build Cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --locked
  release:
    name: Release
    needs:
    - build
    - build-aarch64
    - test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: ./build
    - uses: actions/download-artifact@v3
      with:
        name: build-aarch64
        path: ./build-aarch64
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          build/mvps-te
          build/mvps-s3-gc
          build/nbdstress
        prerelease: true
